apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-operator
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: jenkins-operator
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: quay.io/redhat-developer/openshift-jenkins-operator:latest
        imagePullPolicy: Always
        name: manager
      terminationGracePeriodSeconds: 10
