# permissions for end users to view jenkinsimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkinsimage-viewer-role
rules:
- apiGroups:
  - jenkins.io
  resources:
  - jenkinsimages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jenkins.io
  resources:
  - jenkinsimages/status
  verbs:
  - get
