# permissions for end users to view backupvolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupvolume-viewer-role
rules:
- apiGroups:
  - jenkins.io
  resources:
  - backupvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jenkins.io
  resources:
  - backupvolumes/status
  verbs:
  - get
