apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: jenkins-sample
spec:
  configurationAsCode:
    configurations: []
    enabled: true
    defaultConfig: true
    enableAutoReload: true
